name: Scheduled and Manual Workflow with Inputs

on:
  workflow_dispatch:
    inputs:
      client_name:
        type: string
        required: true
        description: Enter the client name without .yml extension
        default: 'regressionv1'
      environment:
        type: choice
        required: true
        description: Environment (dev/qa/integration)
        options:
          - dev
          - qa
          - integration
        default: qa

  schedule:
    - cron: "* * * * *" # Runs daily at 12:30 AM UTC

jobs:
  run-scheduled-and-manual-task:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Build dynamic parameters for inputs
      - name: Build parameters
        run: |
          # Default values for scheduled runs
          DEFAULT_CLIENT_NAME="regressionv1"
          DEFAULT_ENVIRONMENT="qa"

          # Set inputs dynamically based on trigger
          CLIENT_NAME=${{ github.event.inputs.client_name || DEFAULT_CLIENT_NAME }}
          ENVIRONMENT=${{ github.event.inputs.environment || DEFAULT_ENVIRONMENT }}


          # Save values to environment variables
          echo "CLIENT_NAME=$CLIENT_NAME" >> $GITHUB_ENV
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV


          # Print for debugging
          echo "Parameters: Client name = $CLIENT_NAME, Environment = $ENVIRONMENT"
        shell: bash

      # Example: Checkout specific app properties
      - name: Checkout app properties in data extraction
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            DataExtraction/application.properties
          sparse-checkout-cone-mode: false
          repository: OptumInsight-Analytics/dap-data-extraction
          path: './dataextraction'
          ref: 'main'
          token: ${{ secrets.GIT_TOKEN }}



      # Example: Use the release version dynamically
      - name: Print final release version
        run: |
          echo "The final release version is: ${{ github.event.inputs.client_name }}"
