name: Unzip and Commit Files

on:
  workflow_dispatch: # Manual trigger

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip specific file
        run: |
          unzip ".optum/regression/regression copy.zip" -d .optum/regression/

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit unzipped files
        run: |
          git add ./PATH/TO/*
          git commit -m "Unzipped and committed files from YOUR_ZIP_FILENAME.zip" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
